import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import AOSProvider from "./components/AOSProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

      

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AOSProvider>
          <header>
            <nav>
              <Navbar />
            </nav>
          </header>

          <main>{children}</main>
          <footer>
            <Footer />
          </footer>
        </AOSProvider>
      </body>
    </html>
  );
}
