import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import AOSProvider from "./components/AOSProvider";

import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className={montserrat.variable}>
      <body className="font-montserrat">
        <AOSProvider>
          <header>
            <nav>
              <Navbar />
            </nav>
          </header>

          <main>{children}</main>
          <footer>
            <Footer />
          </footer>
        </AOSProvider>
      </body>
    </html>
  );
}
